import '../styles/Main.css';
function Main() {
    return (
        <main>
            Naruto, según lo establecido por Jiraiya, tiene un gran parecido con su padre, heredando sus ojos azules y su cabello rubio de punta, de igual forma, de su madre heredó la forma de sus ojos y su cara. Las características físicas más importantes y resaltantes de Naruto son las tres marcas de bigotes en ambas mejillas. Además, el rasgo más mencionado con regularidad antes de la Segunda Parte era su baja estatura para su edad. Después de dos años, Naruto tuvo una racha en su crecimiento, llegando a superar en tamaño a Sakura. Para el final de la Cuarta Guerra Mundial Shinobi, la estatura de Naruto había aumentado hasta casi alcanzar a su padre, y dos años después, fue el más alto de su generación. Durante el epílogo, la estatura de Naruto aumentó a tal punto de superar por una cabeza completa a su esposa Hinata, siendo uno de los más altos de su generación.

Durante su infancia, Naruto utilizó una multitud de camisas que variaban sus colores, pasando por blanco, verde o negro, las cuales tenían un símbolo Uzumaki o de fuego en la parte delantera, además de que llevaba unas bermudas. También solía utilizar en su frente unos goggles de color verde que tenían escrito su nombre, sin embargo, con el tiempo, dejó de utilizarlos y lo reemplazó por su banda. Durante la Primera Parte, la vestimenta de Naruto consistió en un chándal color naranja con azul en la zona de los hombros y alrededor de la cintura, un remolino blanco con una borla en la parte izquierda y el símbolo del Clan Uzumaki en la espalda, tenía el cuello alto de color blanco, pantalones color naranja con una pequeña bolsa para guardar sus armas unido a su pierna derecha, las típicas sandalias shinobi de color azul y un protector de frente de color azul. Debajo de su chándal, Naruto utiliza generalmente una camiseta negra, sin embargo, en algunas ocasiones, llevaba una armadura bajo ésta.

Durante la Segunda Parte, la vestimenta de Naruto sufrió modificaciones, debido a que su ropa original fue destrozada durante el entrenamiento con Jiraiya. La vestimenta conserva el color naranja, así como el blanco a excepción de que ya no tenía la borla, además de remolinos de color rojo, sin embargo, el chándal es mucho más ajustada reemplazando el color azul por negro, este se extiende por el cuello, los hombros y en las mangas. La parte metálica de su Banda ninja había sido movida a una larga bandana negra, también cambió sus sandalias shinobi azules por unas negras. En algunas ocasiones, Naruto era visto utilizando una camiseta color verde militar con el símbolo de fuego y pantalones blancos, esto en los días casuales o en los que no haya ninguna misión.

En su batalla contra Pain, Naruto utilizó brevemente una capa roja corta con el diseño de llamas negras en los bordes y llevaba el Pergamino de Invocación de Clones de Sombra colgando en su espalda, sin embargo, la capa fue destruida cuando entr
        </main>
    );
}
export default Main;